### ISSUE TITLE
Wifi with spaces

### ISSUE THREAD

**Issue by marcuslima42** [nksan/Rpi-SetWiFi-viaBluetooth#1]
Hey, cool app!

This works perfectly except for wifi networks that have spaces in the name - it seems to get the SSID wrong perhaps? 

i tried circumventing this by putting in the whole netwrok name as a hidden SSID network, but no luck.

Any thoughts?

**Comment by pierol** [comment]
I have the same problem. SSID with spaces:

1. The app doesn't show the SSID name correctly
2. If i try from app to connect, after inserted the password it failed.

**Comment by nksan** [comment]
I am aware of this.
I will fix with next update of the app. 
Might not happen until early 2024 though.

**Comment by pierol** [comment]
I've modify this line of code (#334) inside btwifiset.py:

```python
ssids = re.findall(r"[^\s]+\s+\d+\s+(-?\d+)\s+([^\s]+)\t+(\b[^\s]+)", out,re.M) 
```
in this:
```python
ssids = re.findall(r"[^\s]+\s+\d+\s+(-?\d+)\s+([^\s]+)\t+(.+)", out,re.M) 
```
and this seems to fix the issue.

**Comment by nksan** [comment]
it does - thanks  - i'll add it in the next version ...  not sure when though

**Comment by pierol** [comment]
I also modify line of code #253 in this:
`python
        ssids = re.findall('(\d+)\s+(.+)\t[^\s]+\t[^\s]+', out, re.M)
`

**Comment by NormFrenette** [comment]
FYI - this has been fixed in the version 2 of the python code which you install from here.  Just run the install script (see README) again, and the code will update accordingly
