### ISSUE TITLE
btwifiset server doesn't start on a Raspberry 3B+

### ISSUE THREAD

**Issue by pierol** [nksan/Rpi-SetWiFi-viaBluetooth#2]
I followed the instructions to install the btwifiset server on a Raspberry 3B+ but it doesn't start, here the log. Do you have any idea why ?
```
> sudo journalctl -f -u btwifiset.service
Oct 19 22:07:51 raspberrypi python3[770]:     props.Set("org.bluez.Adapter1", "Powered", dbus.Boolean(1))
Oct 19 22:07:51 raspberrypi python3[770]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
Oct 19 22:07:51 raspberrypi python3[770]:     return self._proxy_method(*args, **keywords)
Oct 19 22:07:51 raspberrypi python3[770]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
Oct 19 22:07:51 raspberrypi python3[770]:     return self._connection.call_blocking(self._named_service,
Oct 19 22:07:51 raspberrypi python3[770]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
Oct 19 22:07:51 raspberrypi python3[770]:     reply_message = self.send_message_with_reply_and_block(
Oct 19 22:07:51 raspberrypi python3[770]: dbus.exceptions.DBusException: org.bluez.Error.Failed: Failed
Oct 19 22:07:51 raspberrypi systemd[1]: btwifiset.service: Main process exited, code=exited, status=1/FAILURE
Oct 19 22:07:51 raspberrypi systemd[1]: btwifiset.service: Failed with result 'exit-code'.
```

**Comment by nksan** [comment]
I honestly do not know - never seen a problem like that - clearly within the standard dbus package.
what version of raspbian are you running?
Have you tried a clean install?  
I would be curious to see if you have the problem after a clean OS install.  If so - i could try to reproduce it here.

of course before you do all this - have you run  hciconfig -a  in terminal?  it should tell you if your device is setup properly and if it is UP.

**Comment by pierol** [comment]
Hi @nksan, thank you for your reply.
The version of raspian is bullseye:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

```

Here the output of `hciconfig -a`:
```
hci0:   Type: Primary  Bus: UART
        BD Address: B8:27:EB:6F:09:FF  ACL MTU: 1021:8  SCO MTU: 64:1
        DOWN
        RX bytes:711 acl:0 sco:0 events:38 errors:0
        TX bytes:442 acl:0 sco:0 commands:38 errors:0
        Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH SNIFF
        Link mode: SLAVE ACCEPT

```
I didn't try on a clean install

**Comment by nksan** [comment]
Hi Pierol,
glad you fixed it.  You might want to search for rfkill - there is a command line interface you could also use without having to connect a screen and keyboard (for next time)
As a general comment, I could check bluetooth status and turn it on in the python code, but so far I have resisted doing this, reasoning that if a pi has Bluetooth turn off (using rfkill or other means) - there must be a reason why the owner of the pi did this - and I should not unilaterally override that.
Of course, the python code being open source, feel free to fork it and add that in if your pi devices tend to have bluetooth turned off by default.

I'll think on it some more...

**Comment by pierol** [comment]
Thank you for the reply @nksan. I think that when you make a fresh install of raspbian OS the BT is switched off as default. 
A suggestion could be a question during the installation process of the package: if you find the BT is switched off tell it during the installation process of the Rpi-SetWiFi-viaBluetooth and ask to switch it on otherwise the btwifiset.service will not boot.
